// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAntKYCVV4m6U-k19t30eiVT2ImBD6Wh2c',
    appId: '1:43501228528:web:0d1651f94bb2bc8ab8cd35',
    messagingSenderId: '43501228528',
    projectId: 'dazzling-rex-345313',
    authDomain: 'dazzling-rex-345313.firebaseapp.com',
    storageBucket: 'dazzling-rex-345313.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvOR8QZ-A6vfr_gLjsmHwC2HeNrnNZ7J8',
    appId: '1:43501228528:android:bfc2d402b60b32f5b8cd35',
    messagingSenderId: '43501228528',
    projectId: 'dazzling-rex-345313',
    storageBucket: 'dazzling-rex-345313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArPk2XxI0dCb2SprAsBbKlqPrQ1F01vrI',
    appId: '1:43501228528:ios:07a3541e9b8e3c8fb8cd35',
    messagingSenderId: '43501228528',
    projectId: 'dazzling-rex-345313',
    storageBucket: 'dazzling-rex-345313.appspot.com',
    iosClientId: '43501228528-43juq890jk4d950auontsf4bctjinvvt.apps.googleusercontent.com',
    iosBundleId: 'com.reachcode.stakr',
  );
}
